title: Ryunosuke Abe
description: "Mathematical Information Lab@ NAIST"
url: "https://ryuuua.github.io"
baseurl: "/rryuua"
theme: minima
lang: ja-JP
author:
email: abe.ryunosuke.at2@naist.ac.jp
minima:
  skin: auto
show_excerpts: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
google_analytics:  # UA-XXXXX-Y or G-XXXX
